version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"

  php:
    image: php:7.3.6-fpm
    ports:
       - "9000:9000"
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=30119036
      - MYSQL_USER=YAM428
      - MYSQL_PASSWORD=30119036
      - MYSQL_DATABASE=final
    ports:
      - "3306:3306"